apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 2
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp-pod
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
